# https://jekyllrb.com/docs/configuration/

# site-wide variables
title: International Congress of Armenian Mycologists # title of site, used in tab name and elsewhere
email: icarmenian.mycologists@gmail.com # default email
google: Tania Kurbessoian # default name to search on Google Scholar
github: ICArmenian-Mycologists # default GitHub user/org, without the @
twitter: IC_ArmenianMyco # default Twitter handle, without the @
instagram: ICArmenian-Mycologists # default Instagram handle, without the @
youtube: ICArmenian-Mycologists # default YouTube channel handle
is_501c3: true
donorbox_campaign_name: free-template-demo
tinyletter_username: interestingnonprofits

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: false

# base directory where site is hosted
# set to "" if hosting at a custom domain, eg yoursite.com
baseurl: ""

# default front matter parameters for markdown files
# defaults can be overridden on a particular page, eg:
# ---
# description: Description unique to this page
# background: images/different-bg-for-this-page.jpg
# ---
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      description: International Congress for Armenian Mycologists are American Armenian mycologists who are interested in collaborating with the international scientific community. # description that will show under search engine results
      background: icons/ICAM-icon.jpg # background image in header and footer
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

#Features under development
#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: #Not yet available
smartergiving_id: #Not yet available
#mailchimp_embed_code: > # Enter Mailchimp post url on next line.
#  //getkyn.us5.list-manage.com/subscribe/post?u=1407d7ee4cd0d47986cd54315&amp;id=cdc32b64fe
#mailchimp_spam_guard: b_753395b9f963c9ea2d6980b7c_9e1559c2f0
