# https://jekyllrb.com/docs/configuration/

# site-wide variables
title: International Congress of Armenian Mycologists # title of site, used in tab name and elsewhere
email: icarmenian.mycologists@gmail.com # default email
google: Tania Kurbessoian # default name to search on Google Scholar
github: ICArmenian-Mycologists # default GitHub user/org, without the @
twitter: IC_ArmenianMyco # default Twitter handle, without the @
instagram: ICArmenian-Mycologists # default Instagram handle, without the @
youtube: ICArmenian-Mycologists # default YouTube channel handle

# base directory where site is hosted
# set to "" if hosting at a custom domain, eg yoursite.com
baseurl: ""

# default front matter parameters for markdown files
# defaults can be overridden on a particular page, eg:
# ---
# description: Description unique to this page
# background: images/different-bg-for-this-page.jpg
# ---
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      description: International Congress for Armenian Mycologists are American Armenian mycologists who are interested in collaborating with the international scientific community. # description that will show under search engine results
      background: icons/ICAM-icon.jpg # background image in header and footer
      layout: default
# automatic citations
auto-cite:
  plugins:
    - name: sources
      input:
        - ../_data/sources.yaml
  output: ../_data/citations.yaml

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-sitemap

# jekyll theme
theme: null
